-- TABLE
CREATE TABLE CLIENTE(ID INTEGER PRIMARY KEY AUTOINCREMENT NOT NULL, NAME VARCHAR(80) NOT NULL, EMAIL VARCHAR(40) NOT NULL, TELEFONE INTEGER);
CREATE TABLE sqlite_sequence(name,seq);
 
-- INDEX
 
-- TRIGGER
 
-- VIEW
 
